---
apiVersion: networkservicemesh.io/v1
kind: NetworkService
metadata:
  name: web-service
spec:
  payload: IP
  matches:
    - match:
      route:
        - destination:
          destinationSelector:
            app: nginx-nse
