---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      networkservicemesh.io/app: "icmp-responder-nse"
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "icmp-responder-nse"
    spec:
      containers:
        - name: sidecar-nse
          image: networkservicemesh/proxy-sidecar-nse:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ADVERTISE_NSE_NAME
              value: "icmp"
            - name: ADVERTISE_NSE_LABELS
              value: "app=icmp-responder-nse"
            - name: TRACER_ENABLED
              value: "true"
            - name: IP_ADDRESS
              value: "10.60.1.0/24"
          resources:
            limits:
              networkservicemesh.io/socket: 1
        - name: alpine
          image: alpine:latest
          command: ['tail', '-f', '/dev/null']
metadata:
  name: nginx-nse
  namespace: default
