FROM tiswanso/kubectl_kind:latest

# set this to branch or $CIRCLE_SHA1
ARG  vl3_branch=master

RUN  git clone https://github.com/tiswanso/examples.git /go/src/github.com/networkservicemesh/examples && \
     cd /go/src/github.com/networkservicemesh/examples && \
     git checkout $vl3_branch

# copy in KinD kubeconfigs
ADD kubeconfigs /etc/kubeconfigs

ADD run_vl3.sh /go/

