---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "gateway-right"
      networkservicemesh.io/impl: "gw-routers"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "gateway-right"
        networkservicemesh.io/impl: "gw-routers"
    spec:
      containers:
        - name: universal-cnf-endpoint
          image: networkservicemesh/universal-cnf-vppagent:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TRACER_ENABLED
              value: "true"
          resources:
            limits:
              networkservicemesh.io/socket: 1
          volumeMounts:
            - mountPath: /etc/universal-cnf/config.yaml
              subPath: config.yaml
              name: universal-cnf-config-volume
      volumes:
        - name: universal-cnf-config-volume
          configMap:
            name: universal-cnf-gateway-right
metadata:
  name: gateway-right
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: universal-cnf-gateway-right
data:
  config.yaml: |
    initactions:
      - command:
          name: "echo"
          args: ["Do attach the PCI device here and assign it an IP address from 10.60.4.0/24"]
    endpoints:
    - name: "gw-routers"
      labels:
        app: "gw-right"
      ipam:
        prefixpool: "10.60.3.0/24"
        routes: ["10.60.4.0/24"]
      ifname: "endpoint0"
