---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: 4g-network
spec:
  payload: IP
  matches:
    - match:
      sourceSelector:
        app: s1-mme
      route:
        - destination:
          destinationSelector:
            app: mme
    - match:
      sourceSelector:
        app: s6a
      route:
        - destination:
          destinationSelector:
            app: mme
    - match:
      sourceSelector:
        app: s11
      route:
        - destination:
          destinationSelector:
            app: mme
    - match:
      sourceSelector:
        app: s5s8-c
      route:
        - destination:
          destinationSelector:
            app: p-gw-c
    - match:
      sourceSelector:
        app: gx
      route:
        - destination:
          destinationSelector:
            app: p-gw-c
    - match:
      sourceSelector:
        app: sxb
      route:
        - destination:
          destinationSelector:
            app: p-gw-c
    - match:
      sourceSelector:
        app: s1-u
      route:
        - destination:
          destinationSelector:
            app: s-gw-u
    - match:
      sourceSelector:
        app: sxa
      route:
        - destination:
          destinationSelector:
            app: s-gw-u
    - match:
      sourceSelector:
        app: s5s8-u
      route:
        - destination:
          destinationSelector:
            app: s-gw-u
    - match:
      sourceSelector:
        app: sgi
      route:
        - destination:
          destinationSelector:
            app: tdf-u
    - match:
      sourceSelector:
        app: sxc
      route:
        - destination:
          destinationSelector:
            app: tdf-u
