---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      networkservicemesh.io/app: "s-gw-u"
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "s-gw-u"
        networkservicemesh.io/impl: "4g-network"
    spec:
      containers:
        - name: sidecar-nse
          image: networkservicemesh/4g-network-sidecar-nse:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "4g-network"
            - name: ENDPOINT_LABELS
              value: "app=s-gw-u"
            - name: TRACER_ENABLED
              value: "true"
            - name: IP_ADDRESS
              value: "10.60.3.0/24"
          resources:
            limits:
              networkservicemesh.io/socket: 1
        - name: s-gw-u
          image: alpine:latest
          command: ["tail", "-f", "/dev/null"]
          imagePullPolicy: IfNotPresent
metadata:
  name: s-gw-u
  namespace: default
