---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      networkservicemesh.io/app: "mme"
  template:
    metadata:
      annotations:
        ns.networkservicemesh.io/endpoints: |
          {
            "name": "4g-network",
            "tracerEnabled": true,
            "networkServices": [
              {"link": "s1-mme", "labels": "app=mme", "ipaddress": "10.60.1.0/24"},
              {"link": "s6a", "labels": "app=mme", "ipaddress": "10.60.2.0/24"},
              {"link": "s11", "labels": "app=mme", "ipaddress": "10.60.3.0/24"}
            ]
          }
      labels:
        networkservicemesh.io/app: "mme"
        networkservicemesh.io/impl: "4g-network"
    spec:
      containers:
        - name: sidecar-nse
          image: networkservicemesh/4g-network-sidecar-nse:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              networkservicemesh.io/socket: 1
          volumeMounts:
            - name: nsm-endpoints
              mountPath: /etc/nsminfo
        - name: mme
          image: alpine:latest
          command: ["tail", "-f", "/dev/null"]
          imagePullPolicy: IfNotPresent
      volumes:
        - name: nsm-endpoints
          downwardAPI:
            items:
              - path: endpoints
                fieldRef:
                  fieldPath: metadata.annotations['ns.networkservicemesh.io/endpoints']
metadata:
  name: mme
  namespace: default
