---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      networkservicemesh.io/app: "s-gw-u"
  template:
    metadata:
      annotations:
        ns.networkservicemesh.io/endpoints: |
          {
            "name": "4g-network",
            "tracerEnabled": true,
            "networkServices": [
              {"link": "s1-u", "labels": "app=s-gw-u", "ipAddress": "10.60.7.0/24"},
              {"link": "sxa", "labels": "app=s-gw-u", "ipAddress": "10.60.8.0/24"},
              {"link": "s5s8-u", "labels": "app=s-gw-u", "ipAddress": "10.60.9.0/24"}
            ]
          }
      labels:
        networkservicemesh.io/app: "s-gw-u"
        networkservicemesh.io/impl: "4g-network"
    spec:
      containers:
        - name: sidecar-nse
          image: networkservicemesh/4g-network-sidecar-nse:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              networkservicemesh.io/socket: 1
          volumeMounts:
            - name: nsm-endpoints
              mountPath: /etc/nsminfo
        - name: s-gw-u
          image: alpine:latest
          command: ["tail", "-f", "/dev/null"]
          imagePullPolicy: IfNotPresent
      volumes:
        - name: nsm-endpoints
          downwardAPI:
            items:
              - path: endpoints
                fieldRef:
                  fieldPath: metadata.annotations['ns.networkservicemesh.io/endpoints']
metadata:
  name: s-gw-u
  namespace: default
