---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "bridge-domain"
      networkservicemesh.io/impl: "bridge"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "bridge-domain"
        networkservicemesh.io/impl: "bridge"
    spec:
      containers:
        - name: bridge-domain
          image: networkservicemesh/bridge-domain-bridge:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "bridge-domain"
            - name: ENDPOINT_LABELS
              value: "app=bridge"
            - name: TRACER_ENABLED
              value: "true"
            - name: IP_ADDRESS
              value: "10.60.1.0/24"
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: bridge-domain
  namespace: default
