---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      networkservicemesh.io/app: "proxy-nsc"
      networkservicemesh.io/impl: "web-service"
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "proxy-nsc"
        networkservicemesh.io/impl: "web-service"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - name: proxy-nsc
          image: networkservicemesh/proxy-proxy-nsc:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CLIENT_NETWORK_SERVICE
              value: "web-service"
            - name: PROXY_HOST
              value: "0.0.0.0:8080"
          ports:
            - containerPort: 8080
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: proxy-nsc
  namespace: default
