
NAME = 4g-network
DESCRIPTION = "4G Network Topology example"
CONTAINERS = sidecar-nse
PODS = client-hss client-p-gw-u client-pcrf client-s-gw-c client-tdf-c endpoint-mme endpoint-p-gw-c endpoint-s-gw-u endpoint-tdf-u
NETWORK_SERVICES = 4g-network
CHECK = scripts/check-connectivity.sh

include $(TOP)/mk/targets.mk
