---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      device: "router2"
  template:
    metadata:
      labels:
        app: "topo"
        device: "router2"
    spec:
      containers:
        - name: sidecar-nsc
          image: networkservicemesh/topology-sidecar-nsc:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              networkservicemesh.io/socket: "1"
          env:
            - name: NS_NETWORKSERVICEMESH_IO
              value: "topo/eth23?link=r2-r3&peerif=eth32"
        - name: sidecar-nse
          image: networkservicemesh/topology-sidecar-nse:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "topo"
            - name: ENDPOINT_LABELS
              value: "device=router2"
            - name: TRACER_ENABLED
              value: "true"
            - name: IP_ADDRESS
              value: "10.60.2.0/24"
          resources:
            limits:
              networkservicemesh.io/socket: 1
        - name: router
          image: networkservicemesh/topology-qrtr:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: startup-config
              mountPath: /etc/quagga/zebra.conf
              subPath: zebra.conf
      volumes:
        - name: startup-config
          configMap:
            name: qrtr-2
metadata:
  name: router2
  namespace: default
---
apiVersion: v1
metadata:
  name: qrtr-2
data:
  zebra.conf: |
    !
    hostname qrtr-2
    !
    interface lo
      ip address 192.0.2.2/32
      exit
    !
kind: ConfigMap
