---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "simple-client"
      networkservicemesh.io/impl: "secure-intranet"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "simple-client"
        networkservicemesh.io/impl: "secure-intranet"
    spec:
      containers:
        - name: alpine-img
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: ["tail", "-f", "/dev/null"]
metadata:
  name: simple-client
  annotations:
    ns.networkservicemesh.io: secure-intranet
