---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "passthrough"
      networkservicemesh.io/impl: "secure-intranet"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "passthrough"
        networkservicemesh.io/impl: "secure-intranet"
    spec:
      containers:
        - name: passthrough
          image: networkservicemesh/secure-intranet-vppagent-endpoint:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "secure-intranet"
            - name: ENDPOINT_LABELS
              value: "app=passthrough-1"
            - name: CLIENT_NETWORK_SERVICE
              value: "secure-intranet"
            - name: CLIENT_LABELS
              value: "app=passthrough-1"
            - name: TRACER_ENABLED
              value: "true"
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: vppagent-passthrough-1
---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "passthrough"
      networkservicemesh.io/impl: "secure-intranet"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "passthrough"
        networkservicemesh.io/impl: "secure-intranet"
    spec:
      containers:
        - name: passthrough
          image: networkservicemesh/secure-intranet-vppagent-endpoint:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "secure-intranet"
            - name: ENDPOINT_LABELS
              value: "app=passthrough-2"
            - name: CLIENT_NETWORK_SERVICE
              value: "secure-intranet"
            - name: CLIENT_LABELS
              value: "app=passthrough-2"
            - name: TRACER_ENABLED
              value: "true"
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: vppagent-passthrough-2
---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "passthrough"
      networkservicemesh.io/impl: "secure-intranet"
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "passthrough"
        networkservicemesh.io/impl: "secure-intranet"
    spec:
      containers:
        - name: passthrough
          image: networkservicemesh/secure-intranet-vppagent-endpoint:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "secure-intranet"
            - name: ENDPOINT_LABELS
              value: "app=passthrough-3"
            - name: CLIENT_NETWORK_SERVICE
              value: "secure-intranet"
            - name: CLIENT_LABELS
              value: "app=passthrough-3"
            - name: TRACER_ENABLED
              value: "true"
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: vppagent-passthrough-3
