// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serviceregistry.proto

package serviceregistry

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d29ae0370b1d1881, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

//Request used to query
type ServiceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ConnectivityDomain   string   `protobuf:"bytes,2,opt,name=connectivityDomain,proto3" json:"connectivityDomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceRequest) Reset()         { *m = ServiceRequest{} }
func (m *ServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceRequest) ProtoMessage()    {}
func (*ServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d29ae0370b1d1881, []int{1}
}

func (m *ServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceRequest.Unmarshal(m, b)
}
func (m *ServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceRequest.Marshal(b, m, deterministic)
}
func (m *ServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceRequest.Merge(m, src)
}
func (m *ServiceRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceRequest.Size(m)
}
func (m *ServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceRequest proto.InternalMessageInfo

func (m *ServiceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceRequest) GetConnectivityDomain() string {
	if m != nil {
		return m.ConnectivityDomain
	}
	return ""
}

//The request used to register a new service or update the existing ones
type ServiceWorkload struct {
	ServiceName          string      `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ConnectivityDomain   string      `protobuf:"bytes,2,opt,name=connectivityDomain,proto3" json:"connectivityDomain,omitempty"`
	Workloads            []*Workload `protobuf:"bytes,3,rep,name=workloads,proto3" json:"workloads,omitempty"`
	Ports                []int32     `protobuf:"varint,4,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServiceWorkload) Reset()         { *m = ServiceWorkload{} }
func (m *ServiceWorkload) String() string { return proto.CompactTextString(m) }
func (*ServiceWorkload) ProtoMessage()    {}
func (*ServiceWorkload) Descriptor() ([]byte, []int) {
	return fileDescriptor_d29ae0370b1d1881, []int{2}
}

func (m *ServiceWorkload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceWorkload.Unmarshal(m, b)
}
func (m *ServiceWorkload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceWorkload.Marshal(b, m, deterministic)
}
func (m *ServiceWorkload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceWorkload.Merge(m, src)
}
func (m *ServiceWorkload) XXX_Size() int {
	return xxx_messageInfo_ServiceWorkload.Size(m)
}
func (m *ServiceWorkload) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceWorkload.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceWorkload proto.InternalMessageInfo

func (m *ServiceWorkload) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceWorkload) GetConnectivityDomain() string {
	if m != nil {
		return m.ConnectivityDomain
	}
	return ""
}

func (m *ServiceWorkload) GetWorkloads() []*Workload {
	if m != nil {
		return m.Workloads
	}
	return nil
}

func (m *ServiceWorkload) GetPorts() []int32 {
	if m != nil {
		return m.Ports
	}
	return nil
}

//Basic workload
type Workload struct {
	Identifier           *WorkloadIdentifier `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	IPAddress            []string            `protobuf:"bytes,2,rep,name=IPAddress,proto3" json:"IPAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Workload) Reset()         { *m = Workload{} }
func (m *Workload) String() string { return proto.CompactTextString(m) }
func (*Workload) ProtoMessage()    {}
func (*Workload) Descriptor() ([]byte, []int) {
	return fileDescriptor_d29ae0370b1d1881, []int{3}
}

func (m *Workload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Workload.Unmarshal(m, b)
}
func (m *Workload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Workload.Marshal(b, m, deterministic)
}
func (m *Workload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Workload.Merge(m, src)
}
func (m *Workload) XXX_Size() int {
	return xxx_messageInfo_Workload.Size(m)
}
func (m *Workload) XXX_DiscardUnknown() {
	xxx_messageInfo_Workload.DiscardUnknown(m)
}

var xxx_messageInfo_Workload proto.InternalMessageInfo

func (m *Workload) GetIdentifier() *WorkloadIdentifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *Workload) GetIPAddress() []string {
	if m != nil {
		return m.IPAddress
	}
	return nil
}

type WorkloadIdentifier struct {
	Cluster              string   `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	PodName              string   `protobuf:"bytes,2,opt,name=podName,proto3" json:"podName,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkloadIdentifier) Reset()         { *m = WorkloadIdentifier{} }
func (m *WorkloadIdentifier) String() string { return proto.CompactTextString(m) }
func (*WorkloadIdentifier) ProtoMessage()    {}
func (*WorkloadIdentifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_d29ae0370b1d1881, []int{4}
}

func (m *WorkloadIdentifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkloadIdentifier.Unmarshal(m, b)
}
func (m *WorkloadIdentifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkloadIdentifier.Marshal(b, m, deterministic)
}
func (m *WorkloadIdentifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkloadIdentifier.Merge(m, src)
}
func (m *WorkloadIdentifier) XXX_Size() int {
	return xxx_messageInfo_WorkloadIdentifier.Size(m)
}
func (m *WorkloadIdentifier) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkloadIdentifier.DiscardUnknown(m)
}

var xxx_messageInfo_WorkloadIdentifier proto.InternalMessageInfo

func (m *WorkloadIdentifier) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *WorkloadIdentifier) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *WorkloadIdentifier) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "svreg.Empty")
	proto.RegisterType((*ServiceRequest)(nil), "svreg.ServiceRequest")
	proto.RegisterType((*ServiceWorkload)(nil), "svreg.ServiceWorkload")
	proto.RegisterType((*Workload)(nil), "svreg.Workload")
	proto.RegisterType((*WorkloadIdentifier)(nil), "svreg.WorkloadIdentifier")
}

func init() { proto.RegisterFile("serviceregistry.proto", fileDescriptor_d29ae0370b1d1881) }

var fileDescriptor_d29ae0370b1d1881 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x6d, 0x9a, 0x86, 0x36, 0xd7, 0xaa, 0x05, 0x8b, 0xa2, 0x50, 0x31, 0x44, 0x99, 0xb2, 0x90,
	0xa1, 0x2c, 0xc0, 0x82, 0x40, 0x30, 0x74, 0x41, 0x60, 0x90, 0x90, 0x10, 0x4b, 0x49, 0x8e, 0xca,
	0xa2, 0x89, 0x83, 0xed, 0x06, 0xe5, 0x8f, 0xf8, 0x0d, 0xfe, 0x0c, 0x91, 0xb8, 0x49, 0x29, 0x30,
	0x74, 0xf3, 0x9d, 0x9f, 0xdf, 0xdd, 0xf3, 0x7b, 0x30, 0x94, 0x28, 0x32, 0x16, 0xa2, 0xc0, 0x19,
	0x93, 0x4a, 0xe4, 0x41, 0x2a, 0xb8, 0xe2, 0xc4, 0x92, 0x99, 0xc0, 0x99, 0xd7, 0x06, 0xeb, 0x2a,
	0x4e, 0x55, 0xee, 0xdd, 0x43, 0xff, 0xae, 0x04, 0x52, 0x7c, 0x5b, 0xa0, 0x54, 0x84, 0x40, 0x2b,
	0x99, 0xc6, 0xe8, 0x18, 0xae, 0xe1, 0xdb, 0xb4, 0x38, 0x93, 0x00, 0x48, 0xc8, 0x93, 0x04, 0x43,
	0xc5, 0x32, 0xa6, 0xf2, 0x4b, 0x1e, 0x4f, 0x59, 0xe2, 0x34, 0x0b, 0xc4, 0x1f, 0x37, 0xde, 0x87,
	0x01, 0x03, 0x4d, 0xfb, 0xc0, 0xc5, 0xeb, 0x9c, 0x4f, 0x23, 0xe2, 0x42, 0x57, 0xaf, 0x74, 0x5d,
	0xd3, 0xaf, 0xb6, 0x36, 0x9d, 0x42, 0x0e, 0xc1, 0x7e, 0xd7, 0xec, 0xd2, 0x31, 0x5d, 0xd3, 0xef,
	0x8e, 0x07, 0x41, 0xa1, 0x2f, 0x58, 0x4e, 0xa5, 0x35, 0x82, 0xec, 0x82, 0x95, 0x72, 0xa1, 0xa4,
	0xd3, 0x72, 0x4d, 0xdf, 0xa2, 0x65, 0xe1, 0x85, 0xd0, 0xa9, 0x56, 0x3c, 0x01, 0x60, 0x11, 0x26,
	0x8a, 0xbd, 0x30, 0x14, 0xc5, 0x86, 0xdd, 0xf1, 0xfe, 0x1a, 0xe3, 0xa4, 0x02, 0xd0, 0x15, 0x30,
	0x39, 0x00, 0x7b, 0x72, 0x73, 0x1e, 0x45, 0x02, 0xa5, 0x74, 0x9a, 0xae, 0xe9, 0xdb, 0xb4, 0x6e,
	0x78, 0x4f, 0x40, 0x7e, 0xbf, 0x27, 0x0e, 0xb4, 0xc3, 0xf9, 0x42, 0x2a, 0x3d, 0xcb, 0xa6, 0xcb,
	0xf2, 0xfb, 0x26, 0xe5, 0x51, 0xf1, 0x4f, 0xa5, 0xfc, 0x65, 0x59, 0xb9, 0x63, 0xd6, 0xee, 0x8c,
	0x3f, 0x0d, 0xe8, 0x50, 0x6d, 0x33, 0x39, 0x85, 0xed, 0xf2, 0x8c, 0xa2, 0xd2, 0xb5, 0xa7, 0x35,
	0xac, 0x59, 0x32, 0xea, 0xe9, 0x7e, 0x19, 0x85, 0x06, 0x39, 0x83, 0xde, 0xed, 0x02, 0x45, 0xae,
	0x71, 0x64, 0xf8, 0xf3, 0x9d, 0x4e, 0xc8, 0xe8, 0x1f, 0x3a, 0xaf, 0x41, 0x8e, 0xa1, 0x4f, 0x31,
	0xe6, 0x19, 0x6e, 0x3a, 0xfa, 0x62, 0xe7, 0x71, 0xb0, 0x16, 0xd8, 0xe7, 0xad, 0x22, 0xb1, 0x47,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x16, 0xa4, 0xae, 0xa9, 0xca, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryClient interface {
	RegisterWorkload(ctx context.Context, in *ServiceWorkload, opts ...grpc.CallOption) (*Empty, error)
	QueryService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceWorkload, error)
	RemoveWorkload(ctx context.Context, in *ServiceWorkload, opts ...grpc.CallOption) (*Empty, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) RegisterWorkload(ctx context.Context, in *ServiceWorkload, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/svreg.Registry/RegisterWorkload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) QueryService(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*ServiceWorkload, error) {
	out := new(ServiceWorkload)
	err := c.cc.Invoke(ctx, "/svreg.Registry/QueryService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) RemoveWorkload(ctx context.Context, in *ServiceWorkload, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/svreg.Registry/RemoveWorkload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServer is the server API for Registry service.
type RegistryServer interface {
	RegisterWorkload(context.Context, *ServiceWorkload) (*Empty, error)
	QueryService(context.Context, *ServiceRequest) (*ServiceWorkload, error)
	RemoveWorkload(context.Context, *ServiceWorkload) (*Empty, error)
}

// UnimplementedRegistryServer can be embedded to have forward compatible implementations.
type UnimplementedRegistryServer struct {
}

func (*UnimplementedRegistryServer) RegisterWorkload(ctx context.Context, req *ServiceWorkload) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorkload not implemented")
}
func (*UnimplementedRegistryServer) QueryService(ctx context.Context, req *ServiceRequest) (*ServiceWorkload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryService not implemented")
}
func (*UnimplementedRegistryServer) RemoveWorkload(ctx context.Context, req *ServiceWorkload) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveWorkload not implemented")
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_RegisterWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceWorkload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).RegisterWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svreg.Registry/RegisterWorkload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).RegisterWorkload(ctx, req.(*ServiceWorkload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_QueryService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).QueryService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svreg.Registry/QueryService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).QueryService(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_RemoveWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceWorkload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).RemoveWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svreg.Registry/RemoveWorkload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).RemoveWorkload(ctx, req.(*ServiceWorkload))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "svreg.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorkload",
			Handler:    _Registry_RegisterWorkload_Handler,
		},
		{
			MethodName: "QueryService",
			Handler:    _Registry_QueryService_Handler,
		},
		{
			MethodName: "RemoveWorkload",
			Handler:    _Registry_RemoveWorkload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviceregistry.proto",
}
