---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      networkservicemesh.io/app: "proxy-nsc"
      networkservicemesh.io/impl: "streamer"
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "proxy-nsc"
        networkservicemesh.io/impl: "streamer"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - name: proxy-nsc
          image: networkservicemesh/proxy-proxy-nsc:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OUTGOING_NSC_NAME
              value: "streamer"
            - name: PROXY_HOST
              value: ":8080"
          resources:
            limits:
              networkservicemesh.io/socket: 1
metadata:
  name: proxy-nsc
  namespace: default
