---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      networkservicemesh.io/app: "source"
      networkservicemesh.io/impl: "streamer"
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "source"
        networkservicemesh.io/impl: "streamer"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - name: sidecar-nse
          image: networkservicemesh/proxy-sidecar-nse:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ADVERTISE_NSE_NAME
              value: "streamer"
            - name: ADVERTISE_NSE_LABELS
              value: "app=source"
            - name: TRACER_ENABLED
              value: "true"
            - name: IP_ADDRESS
              value: "10.60.1.0/24"
          resources:
            limits:
              networkservicemesh.io/socket: 1
        - name: source
          image: networkservicemesh/streamer-streamer:latest
          imagePullPolicy: IfNotPresent
metadata:
  name: source
  namespace: default
