---
apiVersion: networkservicemesh.io/v1alpha1
kind: NetworkService
metadata:
  name: streamer
spec:
  payload: IP
  matches:
    - match:
      route:
        - destination:
          destinationSelector:
            app: source
