NAME = vpp-icmp
CONTAINERS = vppagent-client vppagent-endpoint
PODS = vppagent-client vppagent-endpoint
CHECK = scripts/check_icmp.sh

export VPP_AGENT=ligato/vpp-agent:v2.0.2

include $(TOP)/mk/targets.mk